### ISSUE TITLE
Mor better README.md

### ISSUE THREAD

**Issue by SLimeyMC** [uvraj/Checkerboard-MC#12]
# **pls**
###### .md

- i gotta
 - make some flex with
*\*this\** 
![flexin doe](https://cdn.discordapp.com/attachments/727942099378372628/734746771061997578/2020-07-20_14.21.09.png)
```GLSL
#include "sincethatcool"
```
but i have to admit
- [ ] worst
- [x] good

you @uvraj

**Comment by uvraj** [comment]
yea sure ill add that pic into the readme

**Comment by SLimeyMC** [comment]
:weary:
